### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by myplacedk**
A bit of cleanup in preparation for the change I actually wanted to make.

### CODE REVIEW

**Comment by myplacedk** [comment]
You can see the change I wanted to make here: https://github.com/myplacedk/ESPlorer/compare/myplacedk:cleanup...dtr-rts

By hooking up DTR and RTS to RESET and GPIO0, it becomes much easier to flash new firmware. But then ESPlorer no longer works.
This changes makes ESPlorer work with DTR and RTS connected. There's still a bug that makes the ESP8266 reset when opening the port, but at least it's usable.

**Comment by myplacedk** [comment]
I found a solution to the bug I mentioned, there's now 3 commits in my branch. Watch one commit at a time to see what I did, it's probably easier than studying the result of all 3 at once.

If you accept this pull request, I can make a new pull request with my change.

**Comment by 4refr0nt** [comment]
Hi!

Many thanks for you work!
Please, make a new pull request.

2015-02-23 1:36 GMT+05:00 Niels Ulrik Andersen <notifications@github.com>:

**Comment by myplacedk** [comment]
You need to accept this pull request before I can create one for the second part.

**Comment by 4refr0nt** [comment]
Tomorrow, ok

2015-02-23 2:11 GMT+05:00, Niels Ulrik Andersen <notifications@github.com>:

**Comment by 4refr0nt** [comment]
So sorry for delay. I'm ready now.

**Comment by myplacedk** [comment]
That's okay. :) The next pull request should be ready in a few minutes.

**Pull request merged**
