### PR TITLE
Migrate to maven

### PR DESCRIPTION
**Pull request by ddm**
The project is easier to build using Maven as it is a de-facto standard build tool in the Java world.
Furthermore, Netbeans is not required anymore to build which allows headless builds and continuous integration servers.
That said if the changes break the Netbeans project, let me know and we'll figure it out... I tested the new layout in Netbeans 8.0.2 and everything seems fine.

The changes are as follows:
- created a Maven `pom.xml` file with appropriate dependencies and setup build to create a unique `jar` with all dependencies
- removed any Netbeans specific files (Netbeans can use the Maven `pom.xml` descriptor as a project file)
- removed external dependencies source files (now provided by Maven as jar files)
- moved source files to `src/main/java` (standard Maven layout)
- moved resource files to `src/main/resources` (id.)
- adapted resource file paths in `ESPlorer.java` to match new project layout
- renamed `uploadLUA.png` to `upload.png` to avoid `NullPointerException` (not sure if I did the right thing there)

Please note that some links in the README point to the `ddm/ESPlorer` repo instead of `4refr0nt/ESPlorer`. If you set a [travis.ci](https://travis-ci.org) build don't forget to update the corresponding URL.

### CODE REVIEW

**Comment by ddm** [comment]
I've added back jssc and autocomplete as mentionned in https://gitter.im/4refr0nt/ESPlorer?at=559636f0a41cae0c73d550f6

Everything seems to work fine without the modified libs too but I could only test on OS X 10.10.

**Comment by devsaurus** [comment]
+1

This build environment helped me a lot when experimenting with the code. Installing the mvn environment was all I needed to build flawlessly on Linux.

**Comment by ddm** [comment]
@devsaurus Glad I could be of any help :) Don't hesitate to ping me if you notice any issue with this branch.

**Comment by marcelstoer** [comment]
@4refr0nt Please merge this PR. It would make the lives of a lot of people in your community a lot easier.

**Comment by marcelstoer** [comment]
Victor why was this PR not merged?

**Comment by 4refr0nt** [comment]
conflict with another commits and PR

**Comment by fluxw42** [comment]
@4refr0nt If the conflicts for this issue get resolved by someone, would this PR be merged? If yes, then I'd be happy to take a look at it.

Using maven would:
 - Help contributers to set up their environment in no time
 - Remove the hard dependency on NetBeans IDE
 - Allow you to bump dependencies quite easily
 - Setup CI like Travis to test, build and provide artifacts
 - ...

**Pull request closed without merging**
